<?php
/**
  * @category   Mageants Shippingtracker
  * @package    Mageants_Shippingtracker
  * @copyright  Copyright (c) 2017 Mageants
  * @author     Mageants Team <support@Mageants.com>
  */

if($this->helper('Mageants\Shippingtracker\Helper\Data')->getConfig('shippingtracker_section/shippingtracker_general/shippingtracker_enable')){ 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

	?>
	<li>
		<a href="<?php /* @escapeNotVerified */ echo $storeManager->getStore()->getBaseUrl(); ?>shippingtracker">Track Order</a>
	</li>
<?php } ?>	

