<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order    = $block->getOrder() ?>
<?php if ($_shipment && $_order): ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= /* @escapeNotVerified */  __('Items') ?>
            </th>
            <th class="item-qty">
                <?= /* @escapeNotVerified */  __('Qty') ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_shipment->getAllItems() as $_item): ?>
            <?php
            if ($_item->getOrderItem()->getParentItem()) {
                continue;
            }
            ?>
            <tbody>
            <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
    <?php if($this->helper('Mageants\Shippingtracker\Helper\Data')->getConfig('shippingtracker_section/shippingtracker_general/shippingtracker_enable') == 1): ?>
        <table cellspacing="0" cellpadding="0" border="0" width="650">
            <thead>
            <tr>
                <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"> <?= /* @escapeNotVerified */  __('Track Your Order'); ?></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td style="font-size: 12px; padding: 7px 9px 9px 9px; border-left: 1px solid #EAEAEA;border-bottom: 1px solid #EAEAEA; border-right: 1px solid #EAEAEA;">
                    <?php if ($_order->getTracksCollection()->count()) : ?>
                        <a href="<?php echo $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($_order); ?>">
                            <?php echo __('Track Your Order'); ?></a>
                    <?php else: ?>
                        <p>Shipping Tracking will be available once shipment will be created.</p>
                    <?php endif; ?>
                </td>
            </tr>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
